from goldy.domain.common.error import DomainError, DomainFieldError


class EmptyPhoneNumberError(DomainFieldError): ...


class InvalidPhoneNumberFormatError(DomainFieldError): ...


class EmptyFirstNameError(DomainFieldError): ...


class TooLongNamePartError(DomainFieldError): ...


class EmptyExternalAccountIdError(DomainFieldError): ...


class TooLongExternalAccountIdError(DomainFieldError): ...


class EmptyMessengerUsernameError(DomainFieldError): ...


class TooLongMessengerUsernameError(DomainFieldError): ...


class EmptyBlockReasonError(DomainFieldError): ...


class TooLongBlockReasonError(DomainFieldError): ...


class PlatformAlreadyLinkedError(DomainError): ...


class MessengerAccountNotLinkedError(DomainError): ...


class LastMessengerAccountError(DomainError): ...


class NotificationTargetNotLinkedError(DomainError): ...


class UserAlreadyBlockedError(DomainError): ...


class UserNotBlockedError(DomainError): ...


class UserIsBlockedError(DomainError): ...


class AuthorizationError(DomainError): ...
