from goldy.domain.common.error import DomainFieldError


class EmptySourceIdError(DomainFieldError): ...


class TooLongSourceIdError(DomainFieldError): ...


class EmptySkuError(DomainFieldError): ...


class TooLongSkuError(DomainFieldError): ...


class MalformedSkuError(DomainFieldError): ...


class EmptyProductNameError(DomainFieldError): ...


class TooLongProductNameError(DomainFieldError): ...


class MalformedProductNameError(DomainFieldError): ...


class EmptyUnitOfMeasureError(DomainFieldError): ...


class TooLongUnitOfMeasureError(DomainFieldError): ...
